name: Build and Publish

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  docker-build-and-push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sets Docker image name for latest
        if: ${{ github.ref_name == 'master' }}
        run: |
          echo "DOCKER_IMAGE_NAME=bwibrew/dns-record-updater:latest" >> $GITHUB_ENV

      - name: Sets Docker image name for tag
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "DOCKER_IMAGE_NAME=bwibrew/dns-record-updater:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          platforms: linux/arm/v6,linux/arm/v7,linux/amd64
